title: Simple Social Share
description: Simple Social Share is a simple way of creating social share buttons on your website.
google_analytics: 
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
